export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const TOPANIME_REQUEST = "TOPANIME_REQUEST";
export const TOPANIME_FAILURE = "TOPANIME_FAILURE";
export const TOPANIME_SUCCESS = "TOPANIME_SUCCESS";
